### ISSUE TITLE
documentation for imap

### ISSUE THREAD

**Issue by rintcius** [non/cats#423] opened 2015-07-31 10:23 UTC
@ceedubs gave a great explanation when I asked for a simple example of `imap`. I copied the answer below so that it can be incorporated in the docs later.
Discussion on gitter start here https://gitter.im/non/cats?at=55b5212252d85d450f4037d0

---

@rintcius here is a go at an example:
We have a Semigroup[Long]. Let's say we wanted to use that to create a Semigroup[Date]. If Semigroup were a covariant functor, we could use: Semigroup[Long].map(long => new Date(long)). However, if you think about that, it wouldn't work. This only states how to convert a Long to a Date. If we have two Dates and we want to use the Semigroup[Long] to add them, we have to say how to convert a Date to a Long.
If Semigroup were a contravariant functor, we could do Semigroup[Long].contramap((d: Date) => d.getTime). However, we also couldn't make this work. It states how to convert a Date to a Long, so we could turn two Dates into two Longs and add them to get a combined Long. However, we now need to be able to turn that Long back into a Date, and we haven't said how to do that.
Semigroup forms an invariant functor, so we have to tell it the conversion in both directions. val semigroupDate: Semigroup[Date] = Semigroup[Long].imap(long => new Date(long))((d: Date) => d.getTime)
A covariant functor can still implement the imap type signature. But it does so in a trivial way - it ignores one of the conversions, since it doesn't need to know it.
The invariant functor instance for semigroups is here: https://github.com/non/cats/blob/9c1e69810e6cc3ddaa5abe124683ed47836cee0c/core/src/main/scala/cats/functor/Invariant.scala#L69-L74

**Comment by ceedubs** [comment] 2015-08-29 18:11
Closing as a duplicate of #164

**Closed by ceedubs** 2015-08-29 18:11 UTC
